### ISSUE TITLE
[Linux] Wrong Files/Folders selection due to case sensitivy

### ISSUE THREAD

**Issue by ripps818** [TKMM-Team/Tkmm#17]
When  I tried to install a folder mod it failed to install because it couldn't find `/home/user/.local/share/Totk/config.json` , however the tkmm binary created files at /home/user/.local/share/**t**otk/**C**onfig.json. 

I was able to work around the issue by creating these symbolic:
```
ln -s ~/.local/share/totk ~/.local/share/Totk
ln -s ~/.local/share/totk/Config.json ~/.local/share/totk/config.json
```
There may be more instances of this, but this is what I've run into.

P.S. I've also run into an Arithmetic operation overflow during import of said mod, but one bug report at a time.

**Comment by ArchLeaders** [comment]
Can you provide the full error and stack trace?

**Comment by ripps818** [comment]
``` 
ripps  ~  Downloads  ./tkmm
[Error] System.Exception: /home/ripps/.local/share/Totk/config.json not found
   at TKMM.SarcTool.Core.SarcAssembler..ctor(String modPath, String configPath) in /home/runner/work/Tkmm/Tkmm/lib/TKMM-SARC/TKMM.SarcTool.Core/SarcAssembler.cs:line 48
   at Tkmm.Core.Components.PackageBuilder.<>c__DisplayClass8_0`1.<CopyContentsInternal>b__2() in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Components/PackageBuilder.cs:line 90
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Tkmm.Core.Components.PackageBuilder.CopyContents[T](T item, String sourceFolder, String outputFolder) in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Components/PackageBuilder.cs:line 61
   at Tkmm.Core.Components.ModReaders.FolderModReader.Read(Stream _, String path) in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Components/ModReaders/FolderModReader.cs:line 34
   at Tkmm.Core.Models.Mods.Mod.FromPath(String path) in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Models/Mods/Mod.cs:line 61
   at Tkmm.Helpers.ModHelper.ImportAsync(String arg) in /home/runner/work/Tkmm/Tkmm/src/Tkmm/Helpers/ModHelper.cs:line 104
   at Tkmm.Helpers.ModHelper.<>c__DisplayClass3_0`1.<<Import>b__1>d.MoveNext() in /home/runner/work/Tkmm/Tkmm/src/Tkmm/Helpers/ModHelper.cs:line 35
--- End of stack trace from previous location ---
   at Tkmm.Helpers.ModHelper.Import[T](T arg, Func`2 createMod) in /home/runner/work/Tkmm/Tkmm/src/Tkmm/Helpers/ModHelper.cs:line 34
[Default] Install Failed!
[Default] Installing '/home/ripps/.local/share/yuzu/load/0100F2C0115B6000/TOTK Optimizer/'
[Default] Generating changelogs for ''
[Default] Copying options
[Default] Waiting for build processes
[Error] System.Exception: /home/ripps/.local/share/Totk/config.json not found
   at TKMM.SarcTool.Core.SarcAssembler..ctor(String modPath, String configPath) in /home/runner/work/Tkmm/Tkmm/lib/TKMM-SARC/TKMM.SarcTool.Core/SarcAssembler.cs:line 48
   at Tkmm.Core.Components.PackageBuilder.<>c__DisplayClass8_0`1.<CopyContentsInternal>b__2() in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Components/PackageBuilder.cs:line 90
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Tkmm.Core.Components.PackageBuilder.CopyContents[T](T item, String sourceFolder, String outputFolder) in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Components/PackageBuilder.cs:line 61
   at Tkmm.Core.Components.ModReaders.FolderModReader.Read(Stream _, String path) in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Components/ModReaders/FolderModReader.cs:line 34
   at Tkmm.Core.Models.Mods.Mod.FromPath(String path) in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Models/Mods/Mod.cs:line 61
   at Tkmm.Helpers.ModHelper.ImportAsync(String arg) in /home/runner/work/Tkmm/Tkmm/src/Tkmm/Helpers/ModHelper.cs:line 104
   at Tkmm.Helpers.ModHelper.<>c__DisplayClass3_0`1.<<Import>b__1>d.MoveNext() in /home/runner/work/Tkmm/Tkmm/src/Tkmm/Helpers/ModHelper.cs:line 35
--- End of stack trace from previous location ---
   at Tkmm.Helpers.ModHelper.Import[T](T arg, Func`2 createMod) in /home/runner/work/Tkmm/Tkmm/src/Tkmm/Helpers/ModHelper.cs:line 34
[Default] Install Failed!
[Default] Installing '/home/ripps/.local/share/yuzu/load/0100F2C0115B6000/TOTK Optimizer/'
[Default] Generating changelogs for ''
[Default] Copying options
[Default] Waiting for build processes
Tkmm.Desktop Information: 0 : Loading archived mappings
Tkmm.Desktop Information: 0 : Creating archive cache (this may take a bit)
[Error] System.Exception: /home/ripps/.local/share/Totk/checksums.bin not found
   at TKMM.SarcTool.Core.SarcPackager..ctor(String outputPath, String modPath, String configPath, String checksumPath, Int32[] checkVersions) in /home/runner/work/Tkmm/Tkmm/lib/TKMM-SARC/TKMM.SarcTool.Core/SarcPackager.cs:line 83
   at Tkmm.Core.Components.PackageBuilder.<>c__DisplayClass8_0`1.<CopyContentsInternal>b__2() in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Components/PackageBuilder.cs:line 93
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Tkmm.Core.Components.PackageBuilder.CopyContents[T](T item, String sourceFolder, String outputFolder) in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Components/PackageBuilder.cs:line 61
   at Tkmm.Core.Components.ModReaders.FolderModReader.Read(Stream _, String path) in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Components/ModReaders/FolderModReader.cs:line 34
   at Tkmm.Core.Models.Mods.Mod.FromPath(String path) in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Models/Mods/Mod.cs:line 61
   at Tkmm.Helpers.ModHelper.ImportAsync(String arg) in /home/runner/work/Tkmm/Tkmm/src/Tkmm/Helpers/ModHelper.cs:line 104
   at Tkmm.Helpers.ModHelper.<>c__DisplayClass3_0`1.<<Import>b__1>d.MoveNext() in /home/runner/work/Tkmm/Tkmm/src/Tkmm/Helpers/ModHelper.cs:line 35
--- End of stack trace from previous location ---
   at Tkmm.Helpers.ModHelper.Import[T](T arg, Func`2 createMod) in /home/runner/work/Tkmm/Tkmm/src/Tkmm/Helpers/ModHelper.cs:line 34
[Default] Install Failed!
Unhandled exception. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Avalonia.Threading.AvaloniaSynchronizationContext.Send(SendOrPostCallback d, Object state)
   at Tmds.DBus.Protocol.DBusConnection.Observer.Emit(Exception exception)
   at Tmds.DBus.Protocol.DBusConnection.Observer.Dispose(Exception exception, Boolean removeObserver)
   at Tmds.DBus.Protocol.DBusConnection.Dispose()
   at Tmds.DBus.Protocol.Connection.Disconnect(Exception disconnectReason, DBusConnection trigger)
   at Tmds.DBus.Protocol.DBusConnection.HandleMessages(Exception exception, Message message)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
 ripps  ~  Downloads  ./tkmm
[Error] System.OverflowException: Arithmetic operation resulted in an overflow.
   at TotkCommon.Components.TotkChecksums.FromStream(Stream stream)
   at TotkCommon.Components.TotkChecksums.FromFile(String checksumCachePath)
   at TKMM.SarcTool.Core.ChecksumLookup..ctor(String checksumBin) in /home/runner/work/Tkmm/Tkmm/lib/TKMM-SARC/TKMM.SarcTool.Core/Checksum/ChecksumLookup.cs:line 10
   at TKMM.SarcTool.Core.SarcPackager..ctor(String outputPath, String modPath, String configPath, String checksumPath, Int32[] checkVersions) in /home/runner/work/Tkmm/Tkmm/lib/TKMM-SARC/TKMM.SarcTool.Core/SarcPackager.cs:line 98
   at Tkmm.Core.Components.PackageBuilder.<>c__DisplayClass8_0`1.<CopyContentsInternal>b__2() in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Components/PackageBuilder.cs:line 93
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Tkmm.Core.Components.PackageBuilder.CopyContents[T](T item, String sourceFolder, String outputFolder) in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Components/PackageBuilder.cs:line 61
   at Tkmm.Core.Components.ModReaders.FolderModReader.Read(Stream _, String path) in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Components/ModReaders/FolderModReader.cs:line 34
   at Tkmm.Core.Models.Mods.Mod.FromPath(String path) in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Models/Mods/Mod.cs:line 61
   at Tkmm.Helpers.ModHelper.ImportAsync(String arg) in /home/runner/work/Tkmm/Tkmm/src/Tkmm/Helpers/ModHelper.cs:line 104
   at Tkmm.Helpers.ModHelper.<>c__DisplayClass3_0`1.<<Import>b__1>d.MoveNext() in /home/runner/work/Tkmm/Tkmm/src/Tkmm/Helpers/ModHelper.cs:line 35
--- End of stack trace from previous location ---
   at Tkmm.Helpers.ModHelper.Import[T](T arg, Func`2 createMod) in /home/runner/work/Tkmm/Tkmm/src/Tkmm/Helpers/ModHelper.cs:line 34
[Default] Install Failed!
```

**Comment by ArchLeaders** [comment]
The `Arithmetic operation resulted in an overflow.` likely means that your `checksums.bin` file is outdated.

Run `Help > Download Assets` to resolve the latest dependencies.

**Comment by ripps818** [comment]
> The `Arithmetic operation resulted in an overflow.` likely means that your `checksums.bin` file is outdated.
> 
> Run `Help > Download Assets` to resolve the latest dependencies.

That did indeed fix that problem. Thank you.
