### ISSUE TITLE
Arguement Out Of Range exception

### ISSUE THREAD

**Issue by trollingdeath555** [TKMM-Team/Tkmm#25]
No matter what i try i get errors, this is the current error i got after trying to install a mod. game version is 1.2.1

[Error] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at RsdbMerger.Core.Mergers.RsdbUniqueRowMerger.LogRowChanges(BymlArray vanillaRows, Byml row, UInt64 rsdbNameHash, Int32 version) in /home/runner/work/Tkmm/Tkmm/lib/RsdbMerger/src/RsdbMerger.Core/Mergers/RsdbUniqueRowMerger.cs:line 78
   at RsdbMerger.Core.Mergers.RsdbUniqueRowMerger.CreateChangelog(ReadOnlySpan`1 canonical, ArraySegment`1 data, RsdbFile target, Stream output) in /home/runner/work/Tkmm/Tkmm/lib/RsdbMerger/src/RsdbMerger.Core/Mergers/RsdbUniqueRowMerger.cs:line 38
   at RsdbMerger.Core.Services.RsdbChangelogService.CreateChangelog(RsdbFile target, ArraySegment`1 data) in /home/runner/work/Tkmm/Tkmm/lib/RsdbMerger/src/RsdbMerger.Core/Services/RsdbChangelogService.cs:line 82
   at RsdbMerger.Core.Services.RsdbChangelogService.CreateChangelog(RsdbFile target) in /home/runner/work/Tkmm/Tkmm/lib/RsdbMerger/src/RsdbMerger.Core/Services/RsdbChangelogService.cs:line 69
   at RsdbMerger.Core.Services.RsdbChangelogService.<CreateChangelogsAsync>b__5_0(RsdbFile target, CancellationToken cancellationToken) in /home/runner/work/Tkmm/Tkmm/lib/RsdbMerger/src/RsdbMerger.Core/Services/RsdbChangelogService.cs:line 54
   at System.Threading.Tasks.Parallel.<>c__53`1.<<ForEachAsync>b__53_0>d.MoveNext()
--- End of stack trace from previous location ---
   at RsdbMerger.Core.Services.RsdbChangelogService.CreateChangelogsAsync() in /home/runner/work/Tkmm/Tkmm/lib/RsdbMerger/src/RsdbMerger.Core/Services/RsdbChangelogService.cs:line 53
   at Tkmm.Core.Components.PackageBuilder.<>c__DisplayClass8_0`1.<<CopyContentsInternal>b__1>d.MoveNext() in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Components/PackageBuilder.cs:line 94
--- End of stack trace from previous location ---
   at Tkmm.Core.Components.PackageBuilder.CopyContents[T](T item, String sourceFolder, String outputFolder) in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Components/PackageBuilder.cs:line 66

![image](https://github.com/TKMM-Team/Tkmm/assets/37271027/b1b4adb5-a632-42ee-90f4-74d792d8b752)

**Comment by ArchLeaders** [comment]
What mod are you trying to install?

**Comment by trollingdeath555** [comment]
I am attempting to install the second quest mod i have quickly tested installing other mods which i have been able to heres my logs.
[log.txt](https://github.com/user-attachments/files/16042761/log.txt)

**Comment by trollingdeath555** [comment]
i at first assumed it was an issue with my dump but it seems like its only happening for that specfic mod

**Comment by ArchLeaders** [comment]
Are you using the latest version of TKMM?

**Comment by trollingdeath555** [comment]
I downloaded the latest version but when i opned it i was prompted to update TKMM which i did

**Comment by trollingdeath555** [comment]
an update i tried installing another mod and this one didnt work either giving me the exact same error. The mod:https://gamebanana.com/mods/494687

**Comment by ArchLeaders** [comment]
> I downloaded the latest version but when i opned it i was prompted to update TKMM which i did

Hm. The latest version should write information to the log, but it's not there. Can you send a screenshot of the about page? (Help > About)

**Comment by trollingdeath555** [comment]
![image](https://github.com/TKMM-Team/Tkmm/assets/37271027/c7d6d492-02db-4805-b42c-bf354af3ff66)

**Comment by ArchLeaders** [comment]
This must be an issue with your game dump then. It works fine for me on `beta6`.

@MasterBubbles also noticed an error that indicates your ZsDic files are also missing, which heavily indicates a corrupt game dump.

I recommend dumping the game for your switch again.
