### ISSUE TITLE
[Bug] PchTxt Parser Error (Comments not expected in data section)

### ISSUE THREAD

**Issue by AmyL4** [TKMM-Team/Tkmm#28]
I keep getting this error when merging and I can't figure out the cause

[Error] System.FormatException: The input string '@K' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Byte.Parse(ReadOnlySpan`1 s, NumberStyles style, IFormatProvider provider)
   at IPS.NET.Core.Converters.PchtxtToIPS.ConvertPchtxtToIps(ReadOnlySpan`1 text, Stream output) in /home/runner/work/Tkmm/Tkmm/lib/IPS.NET/IPS.NET.Core/Converters/PchtxtToIPS.cs:line 103
   at Tkmm.Core.Components.Mergers.ExefsMerger.Merge(IModItem[] mods, String output) in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Components/Mergers/ExefsMerger.cs:line 91
   at Tkmm.Core.Services.MergerService.MergeAsync(IModItem[] mods, String output) in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Services/MergerService.cs:line 70
   at Tkmm.Core.Services.MergerService.<>c__DisplayClass4_0.<<Merge>b__2>d.MoveNext() in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Services/MergerService.cs:line 57
--- End of stack trace from previous location ---
   at Tkmm.Core.Services.MergerService.Merge(Profile profile, String output) in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Services/MergerService.cs:line 55
   at Tkmm.Core.Services.MergerService.Merge() in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Services/MergerService.cs:line 23
   at Tkmm.Helpers.MergerOperations.Merge() in /home/runner/work/Tkmm/Tkmm/src/Tkmm/Helpers/MergerOperations.cs:line 15

**Comment by ArchLeaders** [comment]
@The5thTear This is probably an issue with the pchtxt parser. I'm guessing someone put comments inside the start/end tags of a pchtxt file.

@AmyL4 can you provide the `exefs` folder of the mod causing this issue?

**Comment by AmyL4** [comment]
> @The5thTear This is probably an issue with the pchtxt parser. I'm guessing someone put comments inside the start/end tags of a pchtxt file.
> 
> @AmyL4 can you provide the `exefs` folder of the mod causing this issue?

Here it is in a zip
[exefs.zip](https://github.com/user-attachments/files/16282655/exefs.zip)

**Comment by ArchLeaders** [comment]
That doesn't look right. Do you have another mod with an exefs folder?

**Comment by AmyL4** [comment]
> That doesn't look right. Do you have another mod with an exefs folder?

The only mod I remember having exefs is the exefs generated by totk optimizer (which I keep out of tkmm). I attempted to merge the same mods that merged successfully prior. 

This is the exefs from my old merged mod:
[exefs.zip](https://github.com/user-attachments/files/16287776/exefs.zip)

but I can't merge a new one without getting the error

**Comment by ArchLeaders** [comment]
The `exefs` will be in one of the individual mods installed in TKMM (the files I need will not be part of the merged output). I can probably recreate the issue without it though.

**Comment by ArchLeaders** [comment]
Waiting for https://github.com/The5thTear/IPS.NET/pull/2
