### ISSUE TITLE
cant start TKMM: Unhandled exception. System.TypeInitializationException: The type initializer for 'Tkmm.Core.Components.AppManager' threw an exception.

### ISSUE THREAD

**Issue by Mirek932** [TKMM-Team/Tkmm#29]
if i start TKMM i get this error message:

Unhandled exception. System.TypeInitializationException: The type initializer for 'Tkmm.Core.Components.AppManager' threw an exception.

 ---> System.TypeInitializationException: The type initializer for 'ConfigFactory.Core.ConfigModule`1' threw an exception.
 ---> System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Stream utf8Json)
   at ConfigFactory.Core.ConfigModule`1.Load(T& module)
   at ConfigFactory.Core.ConfigModule`1.<>c.<.cctor>b__43_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at ConfigFactory.Core.ConfigModule`1..cctor()
   --- End of inner exception stack trace ---
   at ConfigFactory.Core.ConfigModule`1.get_Shared()
   at Tkmm.Core.Components.AppManager..cctor() in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Components/AppManager.cs:line 29
   --- End of inner exception stack trace ---
   at Tkmm.Core.Components.AppManager.Start(String[] args, Func`2 attach) in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Core/Components/AppManager.cs:line 41
   at Tkmm.Desktop.Program.Main(String[] args) in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Desktop/Program.cs:line 23

How can i fix it?

**Comment by ArchLeaders** [comment]
As a workaround, delete `%localappdata%\tkmm\Config.json`. However, this has been fixed in https://github.com/TKMM-Team/Tkmm/commit/2bb7101de83aef861e799b334946ca20dcdfee8a
