### ISSUE TITLE
Melon Speedruns' randomizer fails to install with GDL Error "Deletion of array elements is not supported in DefaultValue"

### ISSUE THREAD

**Issue by DisBot404** [TKMM-Team/Tkmm#51]
Melon Speedrun's randomizer completely fails to install in TKMM using any version, this was tested using a compiled version from the latest commit.

```
[Error] System.NotSupportedException: Deletion of array elements is not supported in DefaultValue: 1055395112 in table Enum
   at TKMM.SarcTool.Core.GameDataListMerger.ReconcileChanges(Byml modified, Byml vanilla, String table) in C:\Users\%username%\Documents\GitHub\Tkmm\lib\TKMM-SARC\TKMM.SarcTool.Core\GameDataList\GameDataListMerger.cs:line 702
   at TKMM.SarcTool.Core.GameDataListMerger.CreateChangelog(BymlMap vanilla, BymlMap modified) in C:\Users\%username%\Documents\GitHub\Tkmm\lib\TKMM-SARC\TKMM.SarcTool.Core\GameDataList\GameDataListMerger.cs:line 645
   at TKMM.SarcTool.Core.GameDataListMerger.Package(Memory`1 vanillaBytes, Memory`1 modifiedBytes) in C:\Users\%username%\Documents\GitHub\Tkmm\lib\TKMM-SARC\TKMM.SarcTool.Core\GameDataList\GameDataListMerger.cs:line 76
   at TKMM.SarcTool.Core.SarcPackager.PackageGameDataList() in C:\Users\%username%\Documents\GitHub\Tkmm\lib\TKMM-SARC\TKMM.SarcTool.Core\SarcPackager.cs:line 318
   at TKMM.SarcTool.Core.SarcPackager.InternalMakePackage() in C:\Users\%username%\Documents\GitHub\Tkmm\lib\TKMM-SARC\TKMM.SarcTool.Core\SarcPackager.cs:line 174
   at TKMM.SarcTool.Core.SarcPackager.Package() in C:\Users\%username%\Documents\GitHub\Tkmm\lib\TKMM-SARC\TKMM.SarcTool.Core\SarcPackager.cs:line 112
   at Tkmm.Core.Components.PackageBuilder.<>c__DisplayClass8_0`1.<CopyContentsInternal>b__2() in C:\Users\%username%\Documents\GitHub\Tkmm\src\Tkmm.Core\Components\PackageBuilder.cs:line 107
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Tkmm.Core.Components.PackageBuilder.CopyContents[T](T item, String sourceFolder, String outputFolder) in C:\Users\%username%\Documents\GitHub\Tkmm\src\Tkmm.Core\Components\PackageBuilder.cs:line 66
```

**Comment by DisBot404** [comment]
Turns out, with the latest commit of the randomizer, it works fine, atleast to my testing.
