### ISSUE TITLE
tkmm dosent work

### ISSUE THREAD

**Issue by kkkbbb12** [TKMM-Team/Tkmm#55]
tkmm dosen't open for some reason it says this:

System.TypeInitializationException: The type initializer for 'ConfigFactory.Core.ConfigModule`1' threw an exception.
 ---> System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Stream utf8Json)
   at ConfigFactory.Core.ConfigModule`1.Load(T& module)
   at ConfigFactory.Core.ConfigModule`1.<>c.<.cctor>b__43_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at ConfigFactory.Core.ConfigModule`1..cctor()
   --- End of inner exception stack trace ---
   at ConfigFactory.Core.ConfigModule`1.get_Shared()
   at Tkmm.App.OnFrameworkInitializationCompleted() in /home/runner/work/Tkmm/Tkmm/src/Tkmm/App.axaml.cs:line 119
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at Tkmm.Desktop.Program.Main(String[] args) in /home/runner/work/Tkmm/Tkmm/src/Tkmm.Desktop/Program.cs:line 28

**Comment by ArchLeaders** [comment]
Delete `%localappdata%\totk\Config.json` and `%localappdata%\tkmm\Config.json`
